<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Prakashs-MacBook-Pro.local" failures="1" tests="8" name="Login Page Test" time="18.904" errors="0" timestamp="2024-01-26T20:28:28 IST">
  <testcase classname="com.qa.opencart.tests.LoginPageTest" name="loginPageTitleTest" time="5.384">
    <skipped/>
  </testcase> <!-- loginPageTitleTest -->
  <testcase classname="com.qa.opencart.tests.LoginPageTest" name="loginPageTitleTest" time="5.148">
    <failure type="java.lang.AssertionError" message="expected [Account Login11] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [Account Login11] but found [null]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at com.qa.opencart.tests.LoginPageTest.loginPageTitleTest(LoginPageTest.java:30)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:248)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:481)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
    </failure>
  </testcase> <!-- loginPageTitleTest -->
  <testcase classname="com.qa.opencart.tests.LoginPageTest" name="loginPageURLTest" time="0.008"/>
  <testcase classname="com.qa.opencart.tests.LoginPageTest" name="forgotPwdLinkExistTest" time="0.639"/>
  <testcase classname="com.qa.opencart.tests.LoginPageTest" name="appLogoExistTest" time="0.657"/>
  <testcase classname="com.qa.opencart.tests.LoginPageTest" name="informationExistTest" time="0.652"/>
  <testcase classname="com.qa.opencart.tests.LoginPageTest" name="customerService" time="0.611"/>
  <testcase classname="com.qa.opencart.tests.LoginPageTest" name="loginTest" time="2.826"/>
</testsuite> <!-- Login Page Test -->
