<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Prakashs-MacBook-Pro.local" failures="3" tests="6" name="Negative Login Test" time="6.734" errors="0" timestamp="2024-01-28T08:49:01 IST">
  <testcase classname="com.qa.opencart.tests.LoginPageNegativeTest" name="loginTest" time="0.597">
    <skipped/>
  </testcase> <!-- loginTest -->
  <testcase classname="com.qa.opencart.tests.LoginPageNegativeTest" name="loginTest" time="0.551">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.qa.opencart.tests.LoginPageNegativeTest.loginTest(LoginPageNegativeTest.java:25)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- loginTest -->
  <testcase classname="com.qa.opencart.tests.LoginPageNegativeTest" name="loginTest" time="0.542">
    <skipped/>
  </testcase> <!-- loginTest -->
  <testcase classname="com.qa.opencart.tests.LoginPageNegativeTest" name="loginTest" time="0.548">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.qa.opencart.tests.LoginPageNegativeTest.loginTest(LoginPageNegativeTest.java:25)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- loginTest -->
  <testcase classname="com.qa.opencart.tests.LoginPageNegativeTest" name="loginTest" time="0.6">
    <skipped/>
  </testcase> <!-- loginTest -->
  <testcase classname="com.qa.opencart.tests.LoginPageNegativeTest" name="loginTest" time="0.541">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.qa.opencart.tests.LoginPageNegativeTest.loginTest(LoginPageNegativeTest.java:25)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- loginTest -->
</testsuite> <!-- Negative Login Test -->
